// This file is generated by Prisma and manages CLI environment database URLs.
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Set this to your direct/session connection string for CLI migrations
    url: process.env["DIRECT_URL"],
  },
});
